### ISSUE TITLE
Server Console Spam and Timing Out Issues

### ISSUE THREAD

**Issue by AlHadiHabib** [tomkeuper/BWProxy2023#14]
The error I mentioned occurs after getting started, with the server console spamming 3 to 4 times. Then, suddenly or sometimes after 10-12 hours, the server goes idle, and everything starts timing out. Perhaps there's something wrong with Redis and the arenas. Additionally, I suspect another issue related to this error with an addon map selector. The map selector says "/bwmenu Solo, this group doesn't exist," but I can join the group with "/bw join Solo." This issue is occurring with two groups, while the other groups are working fine.

```
[12:52:56 WARN]: Exception in thread "Craft Scheduler Thread - 16" org.apache.commons.lang.UnhandledException: Plugin BWProxy2023 v${gitVer}1.0-SNAPSHOT generated an exception while executing task 28
[12:52:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:52:56 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[12:52:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:52:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:52:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[12:52:56 WARN]: Caused by: java.util.ConcurrentModificationException
[12:52:56 WARN]:        at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
[12:52:56 WARN]:        at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
[12:52:56 WARN]:        at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1054)
[12:52:56 WARN]:        at com.tomkeuper.bedwars.proxy.arenamanager.ArenaManager.getArena(ArenaManager.java:52)
[12:52:56 WARN]:        at com.tomkeuper.bedwars.proxy.connectionmanager.redis.RetrieveArenaTask.run(RetrieveArenaTask.java:35)
[12:52:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64)
[12:52:56 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[12:52:56 WARN]:        ... 4 more
```

**Comment by tomkeuper** [comment]
The issue regarding the map selector should be fixed by the developer who created it. Or the person who added bw2023 support

**Comment by AlHadiHabib** [comment]
Alright.

**Comment by tomkeuper** [comment]
I checked the code and I dont see how it can throw a `ConcurrentModificationException`
Can you check the latest build on discord and see if you can replicate this issue again? If so please send me the whole server log. (DM is allowed)
