### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ImJacko1510** [tomkeuper/BWProxy2023#30]
### Make sure to check before creating a Bug Report

- [X] The issue isn't already found on the Issue tracker.
- [X] My issue is about **BWProxy2023** and not any addon.
- [X] The issue isn't already fixed in a Release or Development Build.
- [ ] I have checked all boxes without reading them.

### Type of problem

Plugin/Server Incompatibility

### What happened?

when i join to a arena, it joins me to the lobby of the arena server or when i leave a game, it kicks me to the main lobby (it suppose to move me to the bedwars lobby)

### Expected Behaviour

not related to papi

### How to Reproduce

Its random, because sometimes the server works normally, sometimes this happen

### Console Log

https://mclo.gs/SlGz74L

### Errors

https://mclo.gs/AsQ7NFm

### Additional Info

Using Carbon Spigot Latest version

Jdk 17

**Comment by ImJacko1510** [comment]
i changed to another redis but now it crashes if i join to any game

https://mclo.gs/cslAtZZ

**Comment by tomkeuper** [comment]
Its not a ConcurrentModificationException its a connection timed out...

[14:19:15 INFO]: [BWProxy2023] ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[33;1m[16:34:02 WARN]: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection timed out
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:251)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:47)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.Protocol.process(Protocol.java:135)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.Protocol.read(Protocol.java:221)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:351)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.Connection.getUnflushedObject(Connection.java:317)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.JedisPubSubBase.process(JedisPubSubBase.java:115)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.JedisPubSubBase.proceed(JedisPubSubBase.java:92)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.Jedis.subscribe(Jedis.java:7941)
[33;1m[16:34:02 WARN]: 	at com.tomkeuper.bedwars.proxy.connectionmanager.redis.RedisConnection.lambda$0(RedisConnection.java:50)
[33;1m[16:34:02 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[33;1m[16:34:02 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[33;1m[16:34:02 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[33;1m[16:34:02 WARN]: Caused by: java.net.SocketException: Connection timed out
[33;1m[16:34:02 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:330)
[33;1m[16:34:02 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
[33;1m[16:34:02 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
[33;1m[16:34:02 WARN]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[33;1m[16:34:02 WARN]: 	at java.base/java.io.InputStream.read(InputStream.java:218)
[33;1m[16:34:02 WARN]: 	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:245)
[33;1m[16:34:02 WARN]: 	... 12 more

**Comment by ImJacko1510** [comment]
Read second log...

https://mclo.gs/AsQ7NFm

**Comment by tomkeuper** [comment]
There is not point in trying to fix an error you get after another error has already been seen... and the concurrent modification exception is not even present in the full logs you added

**Comment by ImJacko1510** [comment]
![image](https://github.com/user-attachments/assets/a43a8caa-8f6e-4caa-8963-98409f3ab005)

**Comment by tomkeuper** [comment]
as I said before the concurrent modification exception is not even present in the full logs you added

**Comment by ImJacko1510** [comment]
bc the other log is related to another problem, idk if is related or not to the concurrent modification, but sometimes it throws that issue

**Comment by ImJacko1510** [comment]
after rebooting the server when concurrent modification exception occurs, the other issue appears
